# Change these first
owner: mhuzaifahkhan # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Doccla
    url: https://www.doccla.com
  - name: Middleware (Dev) Environment
    url: https://dev.mw.doccla.com/
  - name: OTH (Dev) Environment
    url: https://doccla-dev.oth.io/clinician/login/auth

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  theme: light
  baseUrl: /status
  logoUrl: https://cdn.asp.events/CLIENT_CloserSt_D86EA381_5056_B739_5482D50A1A831DDD/companyProfiles/2a1464ef-948c-11ec-910-06e21988b83f-logo.png
  name: Uptime
  introTitle: "**Demo** uptime and status page, powered by @upptime and @github."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/$OWNER/$REPO). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow: /"
  i18n:
    footer: Copyright © 2023
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
